apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudpulse-app
  namespace: cloudpulse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudpulse-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cloudpulse-app
    spec:
      containers:
        - name: cloudpulse-app
          image: 575589967956.dkr.ecr.ap-south-1.amazonaws.com/cloudpulse-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

